pull_request_rules:
  - name: Automatic merge on approval and CI success
    conditions:
      - base=main
      - label="Please Merge"
      - status-success=test (adopt@1.11)
      - status-success=test (adopt@1.8)
      - "#review-requested=0"
    actions:
      merge:
        method: squash
