pull_request_rules:
  - name: Automatic merge on approval and CI success
    conditions:
      - base=main
      - label="please merge"
      - status-success=test (8)
      - status-success=test (11)
      - status-success=test (17)
      - "#review-requested=0"
    actions:
      merge:
        method: squash

  - name: Automatic merge Dependabot PRs (for actions) on CI success
    conditions:
      - base=main
      - author=dependabot[bot]
      - files~=^.github/workflows/
      - status-success=test (8)
      - status-success=test (11)
      - status-success=test (17)
      - "#review-requested=0"
    actions:
      merge:
        method: squash

  - name: Label lib PRs
    conditions:
      - base=main
      - author=scala-steward
    actions:
      label:
        add:
          - dependencies
