pull_request_rules:
  - name: Automatic merge on approval and CI success
    conditions:
      - label="Please Merge"
      - status-success=build
      - base=main
    actions:
      merge:
        method: merge
