addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"  % "3.9.10")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"       % "2.1.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"  % "0.9.34")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"   % "0.6.1")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.9.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.20")
addSbtPlugin("com.github.sbt"            % "sbt-release"   % "1.1.0")
