addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"  % "3.9.7")
addSbtPlugin("com.jsuereth"     % "sbt-pgp"       % "2.0.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"  % "2.4.0")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"  % "0.9.27")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"   % "0.5.3")
addSbtPlugin("org.scoverage"    % "sbt-scoverage" % "1.9.0")
