name: Regenerate Readme (on new tags)

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  regenerate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sleep for 10 minutes while repository metadata is updated
        run: sleep 10m
        shell: bash

      - name: Generate Readme from template
        run: |
          chmod +x ./scripts/updateReadme.sh
          ./scripts/updateReadme.sh

      - name: Add and Commit file
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update readme versions from template'